<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Hoy[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Inicio[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/nacionales?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Nacionales[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/deportes?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Deportes[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/politica?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Politica[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/economia?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Economia[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/internacionales?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Internacionales[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/espectaculo?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Espectáculo[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/salud?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Salud[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/departamentales?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Departamentales[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/tecnologia?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Tecnologia[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/ciencia?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Ciencia[/doap_button]</span>');  ?>
<?php echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/opinion?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Opinion[/doap_button]</span>');  ?>
<?php //echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/suplemento/nosotras?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Nosotras[/doap_button]</span>');  ?>
<?php //echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/aqui-entre-nos?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Aqui Entre Nos[/doap_button]</span>');  ?>
<?php //echo do_shortcode('<span style="margin-right:4px;line-height:2em;">[doap_button url="http://www.laprensa.com.ni/'.$archive_year.'/'.$archive_month.'/'.$archive_day.'/la-prensa-domingo?archive_page=1'.'" style="soft" background="#369" color="#fff" size="2" wide="no" radius="5" icon_color="#fff" text_shadow="0px 0px 0px #fff" class="date-menu"]Domingo[/doap_button]</span>');  ?>
